"""add closed_at to task table

Revision ID: 82132e2ff1eb
Revises: 4667cad285f7
Create Date: 2025-12-05 14:49:24.845480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82132e2ff1eb'
down_revision: Union[str, Sequence[str], None] = '4667cad285f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'closed_at')
    # ### end Alembic commands ###
